### PR TITLE
fix(blocklist): Fix use of setImmediate to work with node 8

### LINKED ISSUE #212: [node8] infinite recursion loading ip blocklist
Seen in travis tests: https://travis-ci.org/mozilla/fxa-customs-server/jobs/295538389

SImple demo program:
```
var log = {
  info: function () {
  },
  error: function () {
  },
  trace: function () {
  }
}

var config = {
  ipBlocklist: {
    updatePollInterval: 1, // 1 Second
    logOnlyLists: [
      './test/mocks/logOnlyList.netset'
    ]
  }
}

var IPBlocklist = require('../../lib/ip_blocklist')(log, config)
var IPBlocklistManager = require('../../lib/ip_blocklist_manager')(log, config)

var lists = [
  './test/mocks/firehol_level1.netset',
  './test/mocks/simple.netset'
]

var ipBlocklist = new IPBlocklist()
ipBlocklist.load(lists[0]) // RangeError: Maximum call stack size exceeded
  .then(function () {
    console.log('loaded ok')
  })

ipBlocklist = new IPBlocklistManager()
ipBlocklist.load(lists[0]) // RangeError: Maximum call stack size exceeded
  .then(function () {
    console.log('loaded ok')
  })
```
Output:
```
/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:487
Promise.prototype._settlePromiseFromHandler = function (
                                                       ^

RangeError: Maximum call stack size exceeded
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:487:56)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/jrgm/gitwork/fxa-customs-server/node_modules/bluebird/js/release/promise.js:684:18)
```

### PR DESCRIPTION
**Pull request by rfk**
Trial balloon to see if this fixes #212; it makes the demo script from that issue work OK, so I'm hopeful...

### CODE REVIEW

**Comment by rfk** [comment]
As with https://github.com/mozilla/fxa-profile-server/pull/291/ we need to make `npm run outdated` print useful info without failing the build.

**Comment by rfk** [comment]
The circleci failure looks like a spurious error:

```
ERROR: Failed to create usr/lib/libstdc++.a: No space left on device
```

The travis tests are passing though.  I don't know what change in node8 caused this error, but I'll be happy enough just to have it fixed.

At your leisure, @jrgm r?

**Comment by vladikoff** [comment]
cc @jrgm

**Comment by vladikoff** [comment]
This is working locally for me 👍

**Pull request merged**
