### PR TITLE
chore(travis): Tell Travis to use #fxa-bots

### PR DESCRIPTION
**Pull request by chilts**

### CODE REVIEW

**Comment by pdehaan** [comment]
@chilts Weird, tests failed...

**Comment by vladikoff** [comment]
We need to figure out what is up with 
```
not ok test/remote/too_many_emails.js ................. 14/15
    Command: "/home/travis/.nvm/v0.10.39/bin/node too_many_emails.js"
    TAP version 13
    ok 1 test server was started
    ok 2 no errors were returned
    ok 3 no errors were returned
    ok 4 first email attempt
    ok 5 resending the code
    ok 6 second email attempt
    ok 7 resending the code
    ok 8 third email attempt
    ok 9 resending the code
    ok 10 fourth email attempt
    ok 11 operation blocked
    ok 12 account is blocked
    ok 13 account no longer blocked
    ok 14 test server has been killed
    not ok 15 test/remote/too_many_emails.js
      ---
        exit:     143
        timedOut: true
        command:  "/home/travis/.nvm/v0.10.39/bin/node too_many_emails.js"
      ...
    
    1..15
    # tests 15
    # pass  14
    # fail  1
    
total ............................................... 354/355
```

**Comment by chilts** [comment]
@vladikoff but they passed after this was merged: https://travis-ci.org/mozilla/fxa-customs-server/builds/69084780

Looks like it might be something on shutdown since all the actual tests in the file pass! Maybe a connection doesn't let go, the event loop stays open and eventually Travis kills the script. Am guessing. Yes, it's a bit strange.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/fxa/issues/9

**Pull request merged**
