### PR TITLE
some *sharp* tools for updating the configs in memcache

### PR DESCRIPTION
**Pull request by dannycoates**
@jrgm is this good enough or do you want more fancy?

### CODE REVIEW

**Comment by rfk** [comment]
Sharp indeed, but I think there's value in getting this out the door in the next release, and continuing to iterate as follow-ups if we need to.  r+ on the code side from me, will sync up with @jrgm for feedback before merging.

**Comment by jrgm** [comment]
LGTM

**Comment by jrgm** [comment]
One note: `chmod +x ./scripts/config-set.js`

**Comment by dannycoates** [comment]
Thanks @jrgm!

> chmod +x ./scripts/config-set.js

fixed

**Pull request merged**
